export interface Movie {
  title: string;
  year: number;
  genre: string;
  runtime: number;
  director: string;
  rating: number;
}

export const movies: Movie[] = [
  {
    title: 'Shadow of the Azure Vale',
    year: 1983,
    genre: 'Drama',
    runtime: 112,
    director: 'Alex Carter',
    rating: 7.4,
  },
  {
    title: 'Whispers of the Forgotten Coast',
    year: 1999,
    genre: 'Thriller',
    runtime: 101,
    director: 'Taylor Reeves',
    rating: 8.1,
  },
  {
    title: 'Lanterns Beneath the Silent Sky',
    year: 1974,
    genre: 'Fantasy',
    runtime: 118,
    director: 'Morgan Hayes',
    rating: 6.9,
  },
  {
    title: 'Echoes of Hollow Ridge',
    year: 2007,
    genre: 'Mystery',
    runtime: 95,
    director: 'Jamie Foster',
    rating: 7.2,
  },
  {
    title: 'Autumn Blades of Crescent Valley',
    year: 1968,
    genre: 'Action',
    runtime: 132,
    director: 'Reese Turner',
    rating: 6.8,
  },
  {
    title: 'Cinder Paths of the Silent Realm',
    year: 1988,
    genre: 'Drama',
    runtime: 104,
    director: 'Alex Smith',
    rating: 7.1,
  },
  {
    title: 'Gilded Storms of Arcadia',
    year: 2002,
    genre: 'Fantasy',
    runtime: 121,
    director: 'Morgan Johnson',
    rating: 7.8,
  },
  {
    title: 'Harbor Lights of the Northern Gate',
    year: 1979,
    genre: 'Romance',
    runtime: 97,
    director: 'Taylor Reeves',
    rating: 6.9,
  },
  {
    title: 'Iron Echoes of the Fallen Star',
    year: 1995,
    genre: 'Sci-Fi',
    runtime: 113,
    director: 'Jordan Carter',
    rating: 7.5,
  },
  {
    title: 'Shadows Over Briarwind Pass',
    year: 1961,
    genre: 'Thriller',
    runtime: 102,
    director: 'Casey Anders',
    rating: 7.0,
  },
  {
    title: 'Lanternfire at Meridian Shore',
    year: 2018,
    genre: 'Adventure',
    runtime: 110,
    director: 'Robin Bennett',
    rating: 7.6,
  },
  {
    title: 'Moonrise of the Forgotten Orchard',
    year: 2009,
    genre: 'Drama',
    runtime: 99,
    director: 'Avery Carter',
    rating: 7.3,
  },
  {
    title: 'Crystal Voices Beyond the Pale',
    year: 1972,
    genre: 'Mystery',
    runtime: 108,
    director: 'Riley Hayes',
    rating: 7.2,
  },
  {
    title: 'Stormbound Trails of Hollowforge',
    year: 1984,
    genre: 'Action',
    runtime: 128,
    director: 'Skyler Foster',
    rating: 7.4,
  },
  {
    title: 'Winter’s Crest at Silverkeep',
    year: 2005,
    genre: 'Fantasy',
    runtime: 134,
    director: 'Jamie Greene',
    rating: 7.9,
  },
  {
    title: 'Embers Over Sundergate',
    year: 1982,
    genre: 'Drama',
    runtime: 103,
    director: 'Harper Walsh',
    rating: 7.2,
  },
  {
    title: 'The Last Voyage to Riverhollow',
    year: 1990,
    genre: 'Adventure',
    runtime: 117,
    director: 'Quinn Ellison',
    rating: 7.5,
  },
  {
    title: 'Sapphire Nights of Briar Cove',
    year: 1977,
    genre: 'Romance',
    runtime: 98,
    director: 'Parker Banks',
    rating: 6.8,
  },
  {
    title: 'Chronicles of the Iron Meridian',
    year: 2011,
    genre: 'Sci-Fi',
    runtime: 129,
    director: 'Sawyer Carter',
    rating: 7.6,
  },
  {
    title: 'Winterlight Across the Emberlands',
    year: 1966,
    genre: 'Fantasy',
    runtime: 111,
    director: 'Rowan Miller',
    rating: 7.3,
  },
  {
    title: 'The Veil of Silent Winds',
    year: 2003,
    genre: 'Thriller',
    runtime: 100,
    director: 'Emerson Turner',
    rating: 7.0,
  },
  {
    title: 'Legends of the Scarlet Expanse',
    year: 1955,
    genre: 'Action',
    runtime: 132,
    director: 'Finley Walsh',
    rating: 7.1,
  },
  {
    title: 'Moonwake Over Asterfield',
    year: 1989,
    genre: 'Mystery',
    runtime: 107,
    director: 'Dakota Carter',
    rating: 7.4,
  },
  {
    title: 'Ashen Tides of the Northern Realm',
    year: 1971,
    genre: 'Drama',
    runtime: 113,
    director: 'Reese Greene',
    rating: 7.3,
  },
  {
    title: 'Lanternsongs of the Hollow March',
    year: 2008,
    genre: 'Fantasy',
    runtime: 125,
    director: 'Kendall Foster',
    rating: 7.7,
  },
  {
    title: 'Rise of the Brass Horizon',
    year: 1996,
    genre: 'Sci-Fi',
    runtime: 120,
    director: 'Alex Harrington',
    rating: 7.4,
  },
  {
    title: 'Footsteps in the Whispering Vale',
    year: 1958,
    genre: 'Mystery',
    runtime: 101,
    director: 'Jordan Reeves',
    rating: 7.0,
  },
  {
    title: 'The Cobalt Gate Prophecy',
    year: 2020,
    genre: 'Fantasy',
    runtime: 135,
    director: 'Casey Banks',
    rating: 8.0,
  },
  {
    title: 'Harbingers of the Sapphire Wastes',
    year: 1987,
    genre: 'Adventure',
    runtime: 118,
    director: 'Taylor Dawson',
    rating: 7.2,
  },
  {
    title: 'Before the Crimson Meridian',
    year: 2001,
    genre: 'Thriller',
    runtime: 103,
    director: 'Morgan Ellison',
    rating: 7.1,
  },
  {
    title: 'The Silent Wardens of Briarspire',
    year: 1975,
    genre: 'Fantasy',
    runtime: 128,
    director: 'Jamie Kensington',
    rating: 7.4,
  },
  {
    title: 'Glass Towers Over Moonshore',
    year: 1993,
    genre: 'Drama',
    runtime: 109,
    director: 'Harper Dawson',
    rating: 7.3,
  },
  {
    title: 'The Twilight Bridge of Emberwatch',
    year: 2017,
    genre: 'Adventure',
    runtime: 124,
    director: 'Avery Clark',
    rating: 7.8,
  },
  {
    title: 'Whispers at the Frosted Gate',
    year: 1969,
    genre: 'Mystery',
    runtime: 97,
    director: 'Riley Carter',
    rating: 6.9,
  },
  {
    title: 'Voyagers to the Golden Frontier',
    year: 1980,
    genre: 'Action',
    runtime: 130,
    director: 'Skyler Hayes',
    rating: 7.5,
  },
  {
    title: 'The Hidden Chronicle of Starfall',
    year: 1998,
    genre: 'Fantasy',
    runtime: 122,
    director: 'Parker Greene',
    rating: 7.6,
  },
  {
    title: 'Nightfall Over Ivory Spire',
    year: 2006,
    genre: 'Thriller',
    runtime: 104,
    director: 'Rowan Wright',
    rating: 7.2,
  },
  {
    title: 'Banners of the Silver Expanse',
    year: 1957,
    genre: 'Adventure',
    runtime: 116,
    director: 'Emerson Walsh',
    rating: 7.1,
  },
  {
    title: 'Scarlet Dreams Beneath the Wind',
    year: 1973,
    genre: 'Romance',
    runtime: 94,
    director: 'Finley Carter',
    rating: 6.8,
  },
  {
    title: 'The Gilded Voyage of Dawnspire',
    year: 2012,
    genre: 'Fantasy',
    runtime: 131,
    director: 'Dakota Turner',
    rating: 7.9,
  },
  {
    title: 'Citadel of the Fallen Comet',
    year: 1991,
    genre: 'Sci-Fi',
    runtime: 118,
    director: 'Reese Foster',
    rating: 7.4,
  },
  {
    title: 'The Ashen Script of Hollowdeep',
    year: 1964,
    genre: 'Mystery',
    runtime: 102,
    director: 'Kendall Ellison',
    rating: 7.1,
  },
  {
    title: 'Winds of the Sapphire Frontier',
    year: 1985,
    genre: 'Adventure',
    runtime: 115,
    director: 'Alex Hayes',
    rating: 7.3,
  },
  {
    title: 'The Ironstar Testament',
    year: 2004,
    genre: 'Drama',
    runtime: 110,
    director: 'Jordan Harrington',
    rating: 7.2,
  },
  {
    title: 'Crimson Echoes of the Outer Gate',
    year: 2019,
    genre: 'Sci-Fi',
    runtime: 133,
    director: 'Taylor Banks',
    rating: 7.7,
  },
  {
    title: 'Legends from the Frozen Meridian',
    year: 1953,
    genre: 'Fantasy',
    runtime: 126,
    director: 'Morgan Walsh',
    rating: 7.2,
  },
  {
    title: 'Return to the Whispering Archipelago',
    year: 1978,
    genre: 'Adventure',
    runtime: 120,
    director: 'Casey Foster',
    rating: 7.1,
  },
  {
    title: 'The Sapphire Lantern Covenant',
    year: 2007,
    genre: 'Fantasy',
    runtime: 127,
    director: 'Jamie Clark',
    rating: 7.8,
  },
  {
    title: 'Threads of the Silent Horizon',
    year: 1994,
    genre: 'Mystery',
    runtime: 99,
    director: 'Harper Carter',
    rating: 7.0,
  },
  {
    title: 'The Crestfall Expedition',
    year: 2015,
    genre: 'Adventure',
    runtime: 123,
    director: 'Avery Hayes',
    rating: 7.6,
  },
  {
    title: 'Moonspire Over the Glass Desert',
    year: 1981,
    genre: 'Sci-Fi',
    runtime: 119,
    director: 'Riley Foster',
    rating: 7.5,
  },
  {
    title: 'Cradle of the Amber Horizon',
    year: 1962,
    genre: 'Drama',
    runtime: 108,
    director: 'Skyler Dawson',
    rating: 7.2,
  },
  {
    title: 'The Starlit Frontier Pact',
    year: 1997,
    genre: 'Fantasy',
    runtime: 132,
    director: 'Parker Turner',
    rating: 7.7,
  },
  {
    title: 'Ashfall Reaches of Whisperwind',
    year: 2000,
    genre: 'Thriller',
    runtime: 101,
    director: 'Rowan Carter',
    rating: 7.1,
  },
  {
    title: 'The Silverborn Legacy',
    year: 1986,
    genre: 'Action',
    runtime: 125,
    director: 'Emerson Greene',
    rating: 7.4,
  },
  {
    title: 'Guardian of the Coastal Labyrinth',
    year: 1970,
    genre: 'Mystery',
    runtime: 96,
    director: 'Finley Banks',
    rating: 7.0,
  },
  {
    title: 'The Golden Aegis of Dawnreach',
    year: 2013,
    genre: 'Adventure',
    runtime: 134,
    director: 'Dakota Harrington',
    rating: 7.8,
  },
  {
    title: 'Voyage to the Silent Bastion',
    year: 1959,
    genre: 'Drama',
    runtime: 111,
    director: 'Reese Walsh',
    rating: 7.1,
  },
  {
    title: 'The Sapphire Rebellion',
    year: 1983,
    genre: 'Sci-Fi',
    runtime: 121,
    director: 'Kendall Carter',
    rating: 7.5,
  },
  {
    title: 'Twilight Over Emberforge',
    year: 1992,
    genre: 'Fantasy',
    runtime: 118,
    director: 'Alex Dawson',
    rating: 7.4,
  },
  {
    title: 'The Obsidian Throne of Starcrest',
    year: 1984,
    genre: 'Fantasy',
    runtime: 124,
    director: 'Jordan Miller',
    rating: 7.6,
  },
  {
    title: 'March of the Verdant Expanse',
    year: 1976,
    genre: 'Adventure',
    runtime: 119,
    director: 'Taylor Wright',
    rating: 7.3,
  },
  {
    title: 'The Frostglen Accord',
    year: 2008,
    genre: 'Drama',
    runtime: 110,
    director: 'Harper Foster',
    rating: 7.2,
  },
  {
    title: 'Moonward Dreams of Hollowpoint',
    year: 1965,
    genre: 'Thriller',
    runtime: 102,
    director: 'Morgan Banks',
    rating: 6.9,
  },
  {
    title: 'The Emberwatch Manifesto',
    year: 1999,
    genre: 'Sci-Fi',
    runtime: 127,
    director: 'Casey Turner',
    rating: 7.7,
  },
  {
    title: 'Voyagers of the Pale Frontier',
    year: 1956,
    genre: 'Adventure',
    runtime: 115,
    director: 'Riley Smith',
    rating: 7.1,
  },
  {
    title: 'Sundering Tides of Bluehaven',
    year: 1981,
    genre: 'Romance',
    runtime: 96,
    director: 'Skyler Carter',
    rating: 6.8,
  },
  {
    title: 'Shatterstar: Requiem of the Iron Vale',
    year: 2014,
    genre: 'Sci-Fi',
    runtime: 133,
    director: 'Parker Hayes',
    rating: 7.8,
  },
  {
    title: 'Autumn Crown of the Scarlet Deep',
    year: 1993,
    genre: 'Drama',
    runtime: 108,
    director: 'Rowan Ellison',
    rating: 7.4,
  },
  {
    title: 'Glass Echoes Across Windspire',
    year: 1971,
    genre: 'Fantasy',
    runtime: 126,
    director: 'Emerson Dawson',
    rating: 7.5,
  },
  {
    title: 'Thunder at the Azure Bastion',
    year: 2005,
    genre: 'Action',
    runtime: 131,
    director: 'Finley Carter',
    rating: 7.6,
  },
  {
    title: 'The Meridian Outriders',
    year: 1987,
    genre: 'Adventure',
    runtime: 118,
    director: 'Dakota Greene',
    rating: 7.2,
  },
  {
    title: 'Crimson Lullabies of Frosthaven',
    year: 1968,
    genre: 'Mystery',
    runtime: 103,
    director: 'Reese Harrington',
    rating: 7.0,
  },
  {
    title: 'The Stormforge Chronicles',
    year: 1997,
    genre: 'Fantasy',
    runtime: 130,
    director: 'Kendall Walsh',
    rating: 7.7,
  },
  {
    title: 'The Pale Lantern Treaty',
    year: 2016,
    genre: 'Drama',
    runtime: 109,
    director: 'Alex Reeves',
    rating: 7.2,
  },
  {
    title: 'Whispers upon the Indigo Strait',
    year: 1954,
    genre: 'Romance',
    runtime: 95,
    director: 'Jamie Banks',
    rating: 6.7,
  },
  {
    title: 'Rise of the Starborne Wardens',
    year: 1982,
    genre: 'Sci-Fi',
    runtime: 128,
    director: 'Harper Miller',
    rating: 7.5,
  },
  {
    title: 'Fogfall Over Silverbridge',
    year: 2001,
    genre: 'Mystery',
    runtime: 101,
    director: 'Avery Wright',
    rating: 7.1,
  },
  {
    title: 'The Hollowspire Annex',
    year: 1979,
    genre: 'Thriller',
    runtime: 99,
    director: 'Riley Dawson',
    rating: 7.0,
  },
  {
    title: 'Citadel Walkers of the Golden Steppe',
    year: 1961,
    genre: 'Adventure',
    runtime: 117,
    director: 'Skyler Turner',
    rating: 7.3,
  },
  {
    title: 'The Frostborn Regalia',
    year: 2013,
    genre: 'Fantasy',
    runtime: 134,
    director: 'Parker Foster',
    rating: 7.8,
  },
  {
    title: 'Cobalt Dreams Beneath the Shifting Sky',
    year: 1992,
    genre: 'Drama',
    runtime: 106,
    director: 'Rowan Hayes',
    rating: 7.2,
  },
  {
    title: 'The Ironwood Expedition',
    year: 1957,
    genre: 'Action',
    runtime: 123,
    director: 'Emerson Carter',
    rating: 7.4,
  },
  {
    title: 'Starhewn Oracles of the Deep',
    year: 1985,
    genre: 'Fantasy',
    runtime: 120,
    director: 'Finley Greene',
    rating: 7.5,
  },
  {
    title: 'Lanternfall at Dawnbreak Point',
    year: 1998,
    genre: 'Adventure',
    runtime: 125,
    director: 'Dakota Walsh',
    rating: 7.6,
  },
  {
    title: 'The Shattered Meridian Pact',
    year: 2007,
    genre: 'Sci-Fi',
    runtime: 129,
    director: 'Reese Carter',
    rating: 7.7,
  },
  {
    title: 'The Sapphire Maw of Briar Hollow',
    year: 1974,
    genre: 'Mystery',
    runtime: 104,
    director: 'Kendall Dawson',
    rating: 7.1,
  },
  {
    title: 'The Whisperwind Edict',
    year: 2021,
    genre: 'Drama',
    runtime: 113,
    director: 'Alex Smith',
    rating: 7.3,
  },
  {
    title: 'Mooncrest Riders of the Eastern Gate',
    year: 1963,
    genre: 'Adventure',
    runtime: 119,
    director: 'Morgan Johnson',
    rating: 7.2,
  },
  {
    title: 'Stormshard of the Forgotten Realm',
    year: 1989,
    genre: 'Fantasy',
    runtime: 132,
    director: 'Taylor Reeves',
    rating: 7.8,
  },
  {
    title: 'The Clockwork Myriad',
    year: 2003,
    genre: 'Sci-Fi',
    runtime: 122,
    director: 'Jordan Carter',
    rating: 7.6,
  },
  {
    title: 'The Luminous Accord of Frostspire',
    year: 1991,
    genre: 'Fantasy',
    runtime: 131,
    director: 'Casey Turner',
    rating: 7.6,
  },
  {
    title: 'Ashen Crowns of the Sapphire Reach',
    year: 1970,
    genre: 'Drama',
    runtime: 108,
    director: 'Jamie Foster',
    rating: 7.2,
  },
  {
    title: 'Voyagers Beyond the Gilded Wastes',
    year: 2009,
    genre: 'Adventure',
    runtime: 118,
    director: 'Harper Dawson',
    rating: 7.5,
  },
  {
    title: 'The Obsidian Ledger',
    year: 1967,
    genre: 'Mystery',
    runtime: 101,
    director: 'Avery Carter',
    rating: 7.1,
  },
  {
    title: 'Starborn Siege of Hollowpoint',
    year: 1986,
    genre: 'Sci-Fi',
    runtime: 129,
    director: 'Riley Hayes',
    rating: 7.7,
  },
  {
    title: 'The Frostveil Covenant',
    year: 2012,
    genre: 'Fantasy',
    runtime: 135,
    director: 'Skyler Greene',
    rating: 7.8,
  },
  {
    title: 'Chronicles of the Verdant Divide',
    year: 1958,
    genre: 'Drama',
    runtime: 112,
    director: 'Parker Carter',
    rating: 7.2,
  },
  {
    title: 'The Hollowforge Codex',
    year: 1980,
    genre: 'Thriller',
    runtime: 104,
    director: 'Rowan Foster',
    rating: 7.0,
  },
  {
    title: 'Crimson Lanterns Across Meridian Way',
    year: 1994,
    genre: 'Romance',
    runtime: 96,
    director: 'Emerson Banks',
    rating: 6.9,
  },
  {
    title: 'Thunderfall at the Azure Peaks',
    year: 2004,
    genre: 'Action',
    runtime: 128,
    director: 'Finley Reeves',
    rating: 7.5,
  },
  {
    title: 'The Celestial Archive',
    year: 2017,
    genre: 'Sci-Fi',
    runtime: 123,
    director: 'Dakota Turner',
    rating: 7.8,
  },
  {
    title: 'Dawnsong of the Scarlet Frontier',
    year: 1962,
    genre: 'Adventure',
    runtime: 117,
    director: 'Reese Carter',
    rating: 7.3,
  },
  {
    title: 'Veil of the Shattered Horizon',
    year: 1983,
    genre: 'Thriller',
    runtime: 101,
    director: 'Kendall Dawson',
    rating: 7.1,
  },
  {
    title: 'The Gilded War of Ironreach',
    year: 1997,
    genre: 'Action',
    runtime: 132,
    director: 'Alex Hayes',
    rating: 7.6,
  },
  {
    title: 'Moonwake Chronicles: Emberfall',
    year: 2006,
    genre: 'Fantasy',
    runtime: 124,
    director: 'Jordan Harrington',
    rating: 7.7,
  },
  {
    title: 'The Sapphire Gale Uprising',
    year: 1955,
    genre: 'Drama',
    runtime: 110,
    director: 'Taylor Banks',
    rating: 7.0,
  },
  {
    title: 'Silent Echoes of the Forgotten Path',
    year: 1978,
    genre: 'Mystery',
    runtime: 98,
    director: 'Morgan Walsh',
    rating: 7.1,
  },
  {
    title: 'The Ironshore Expedition',
    year: 1988,
    genre: 'Adventure',
    runtime: 120,
    director: 'Casey Carter',
    rating: 7.3,
  },
  {
    title: 'Stormcallers of the Shifting Realm',
    year: 2011,
    genre: 'Fantasy',
    runtime: 129,
    director: 'Jamie Clark',
    rating: 7.8,
  },
  {
    title: 'Lanternsong Requiem',
    year: 1969,
    genre: 'Drama',
    runtime: 105,
    director: 'Harper Greene',
    rating: 7.2,
  },
  {
    title: 'Voyage to the Obsidian Shoals',
    year: 1990,
    genre: 'Adventure',
    runtime: 118,
    director: 'Avery Wright',
    rating: 7.4,
  },
  {
    title: 'The Emberfall Paradox',
    year: 2002,
    genre: 'Sci-Fi',
    runtime: 121,
    director: 'Riley Foster',
    rating: 7.6,
  },
  {
    title: 'Shattered Sigils of Briarspire',
    year: 2018,
    genre: 'Fantasy',
    runtime: 133,
    director: 'Skyler Dawson',
    rating: 7.9,
  },
  {
    title: 'The Golden Vow of Windmere',
    year: 1953,
    genre: 'Romance',
    runtime: 95,
    director: 'Parker Turner',
    rating: 6.8,
  },
  {
    title: 'Silent Dominion of Frostglen',
    year: 1981,
    genre: 'Thriller',
    runtime: 102,
    director: 'Rowan Ellison',
    rating: 7.0,
  },
  {
    title: 'Chronicles of the Sapphire Expanse',
    year: 1999,
    genre: 'Fantasy',
    runtime: 129,
    director: 'Emerson Carter',
    rating: 7.7,
  },
  {
    title: 'Ashfall Riders of Meridian Crest',
    year: 1974,
    genre: 'Adventure',
    runtime: 117,
    director: 'Finley Hayes',
    rating: 7.3,
  },
  {
    title: 'The Frostspire Enigma',
    year: 2008,
    genre: 'Mystery',
    runtime: 103,
    director: 'Dakota Greene',
    rating: 7.1,
  },
  {
    title: 'The Iron Lantern Accord',
    year: 1966,
    genre: 'Drama',
    runtime: 110,
    director: 'Reese Turner',
    rating: 7.2,
  },
  {
    title: 'Stormbound Heralds of Briarshore',
    year: 1985,
    genre: 'Action',
    runtime: 126,
    director: 'Kendall Banks',
    rating: 7.6,
  },
  {
    title: 'Moonshard Dreams of Winterdeep',
    year: 2013,
    genre: 'Fantasy',
    runtime: 134,
    director: 'Alex Dawson',
    rating: 7.9,
  },
  {
    title: 'The Scarlet Parable',
    year: 1992,
    genre: 'Drama',
    runtime: 105,
    director: 'Taylor Harrington',
    rating: 7.1,
  },
  {
    title: 'Voyagers of the Silver Frontier',
    year: 1957,
    genre: 'Adventure',
    runtime: 118,
    director: 'Morgan Carter',
    rating: 7.2,
  },
  {
    title: 'The Hollowdeep Cartographer',
    year: 1979,
    genre: 'Mystery',
    runtime: 99,
    director: 'Casey Reeves',
    rating: 7.0,
  },
  {
    title: 'Whispers Beyond the Indigo Reach',
    year: 2004,
    genre: 'Romance',
    runtime: 97,
    director: 'Jamie Foster',
    rating: 6.9,
  },
  {
    title: 'The Emberwake Convergence',
    year: 2019,
    genre: 'Sci-Fi',
    runtime: 133,
    director: 'Harper Miller',
    rating: 7.8,
  },
  {
    title: 'Citadel of the Broken Meridian',
    year: 1963,
    genre: 'Thriller',
    runtime: 102,
    director: 'Avery Dawson',
    rating: 7.0,
  },
  {
    title: 'Rise of the Frostgale Sentinels',
    year: 1983,
    genre: 'Fantasy',
    runtime: 130,
    director: 'Riley Smith',
    rating: 7.7,
  },
  {
    title: 'The Golden Lantern Expedition',
    year: 1997,
    genre: 'Adventure',
    runtime: 121,
    director: 'Skyler Turner',
    rating: 7.5,
  },
  {
    title: 'Mooncrest Covenant of Starhaven',
    year: 2006,
    genre: 'Fantasy',
    runtime: 128,
    director: 'Parker Walsh',
    rating: 7.8,
  },
  {
    title: 'The Frostborn Directive',
    year: 1971,
    genre: 'Action',
    runtime: 123,
    director: 'Rowan Carter',
    rating: 7.4,
  },
  {
    title: 'The Radiant Shores of Aetherwind',
    year: 1955,
    genre: 'Drama',
    runtime: 109,
    director: 'Emerson Greene',
    rating: 7.1,
  },
  {
    title: 'Lanterns Across the Silent Frontier',
    year: 2014,
    genre: 'Adventure',
    runtime: 120,
    director: 'Finley Foster',
    rating: 7.6,
  },
  {
    title: 'The Sapphire Bastion Heist',
    year: 1991,
    genre: 'Thriller',
    runtime: 104,
    director: 'Dakota Ellison',
    rating: 7.2,
  },
  {
    title: 'Winds of the Ember Kingdom',
    year: 1988,
    genre: 'Fantasy',
    runtime: 132,
    director: 'Reese Miller',
    rating: 7.8,
  },
  {
    title: 'The Crystalward Compact',
    year: 2001,
    genre: 'Sci-Fi',
    runtime: 118,
    director: 'Kendall Turner',
    rating: 7.5,
  },
  {
    title: 'Journey Into the Verdant Labyrinth',
    year: 1969,
    genre: 'Adventure',
    runtime: 117,
    director: 'Alex Carter',
    rating: 7.3,
  },
  {
    title: 'The Obsidian Crown Rebellion',
    year: 1982,
    genre: 'Fantasy',
    runtime: 129,
    director: 'Taylor Reeves',
    rating: 7.6,
  },
  {
    title: 'Twilight Over the Shattered Shoals',
    year: 1993,
    genre: 'Drama',
    runtime: 106,
    director: 'Jordan Banks',
    rating: 7.2,
  },
  {
    title: 'The Astral Warden Protocol',
    year: 2010,
    genre: 'Sci-Fi',
    runtime: 124,
    director: 'Jamie Carter',
    rating: 7.7,
  },
  {
    title: 'Banners of the Shifting Meridian',
    year: 1964,
    genre: 'Adventure',
    runtime: 116,
    director: 'Harper Dawson',
    rating: 7.3,
  },
  {
    title: 'Crimson Hourglass of Aetherfall',
    year: 1989,
    genre: 'Thriller',
    runtime: 103,
    director: 'Avery Hayes',
    rating: 7.1,
  },
  {
    title: 'The Frostspire Intervention',
    year: 1996,
    genre: 'Fantasy',
    runtime: 130,
    director: 'Riley Turner',
    rating: 7.8,
  },
  {
    title: 'Echoes from the Cobalt Frontier',
    year: 1959,
    genre: 'Drama',
    runtime: 109,
    director: 'Skyler Reeves',
    rating: 7.0,
  },
  {
    title: 'Voyage of the Emberward Navigators',
    year: 2003,
    genre: 'Adventure',
    runtime: 121,
    director: 'Parker Harrington',
    rating: 7.4,
  },
  {
    title: 'The Ironfold Prophecy',
    year: 1981,
    genre: 'Fantasy',
    runtime: 127,
    director: 'Rowan Miller',
    rating: 7.6,
  },
  {
    title: 'Autumnfall Under the Golden Sky',
    year: 1972,
    genre: 'Romance',
    runtime: 95,
    director: 'Emerson Foster',
    rating: 6.8,
  },
  {
    title: 'The Shattered Codex of Winterdeep',
    year: 2005,
    genre: 'Mystery',
    runtime: 101,
    director: 'Finley Walsh',
    rating: 7.0,
  },
  {
    title: 'Luminant Dominion of the Skybound Gate',
    year: 2018,
    genre: 'Fantasy',
    runtime: 134,
    director: 'Dakota Greene',
    rating: 7.9,
  },
  {
    title: 'The Sapphire Rift Expedition',
    year: 1993,
    genre: 'Sci-Fi',
    runtime: 123,
    director: 'Reese Turner',
    rating: 7.6,
  },
  {
    title: 'Moonveil Chronicle: Ashen Reaches',
    year: 1961,
    genre: 'Drama',
    runtime: 107,
    director: 'Kendall Carter',
    rating: 7.1,
  },
  {
    title: 'The Emberworld Outriders',
    year: 1987,
    genre: 'Action',
    runtime: 128,
    director: 'Alex Hayes',
    rating: 7.5,
  },
  {
    title: 'Voyagers to the Frozen Shoreline',
    year: 1977,
    genre: 'Adventure',
    runtime: 118,
    director: 'Taylor Banks',
    rating: 7.2,
  },
  {
    title: 'The Hollowbrink Cipher',
    year: 2009,
    genre: 'Mystery',
    runtime: 100,
    director: 'Jordan Foster',
    rating: 7.0,
  },
  {
    title: 'Citadelstorm Over Dawnhold',
    year: 1984,
    genre: 'Fantasy',
    runtime: 131,
    director: 'Morgan Reeves',
    rating: 7.7,
  },
  {
    title: 'Lanterns of the Verdant Frontier',
    year: 1956,
    genre: 'Drama',
    runtime: 110,
    director: 'Casey Wright',
    rating: 7.1,
  },
  {
    title: 'Whisperglen Pact of the Amber Coast',
    year: 1999,
    genre: 'Adventure',
    runtime: 119,
    director: 'Jamie Dawson',
    rating: 7.4,
  },
  {
    title: 'The Sapphire Ember Revolt',
    year: 2016,
    genre: 'Fantasy',
    runtime: 133,
    director: 'Harper Carter',
    rating: 7.8,
  },
  {
    title: 'The Ironmist Treaty',
    year: 1968,
    genre: 'Thriller',
    runtime: 103,
    director: 'Avery Greene',
    rating: 7.0,
  },
  {
    title: 'Moonspire of the Golden Wastes',
    year: 1994,
    genre: 'Drama',
    runtime: 108,
    director: 'Riley Turner',
    rating: 7.2,
  },
  {
    title: 'The Astral Vanguard Initiative',
    year: 2007,
    genre: 'Sci-Fi',
    runtime: 126,
    director: 'Skyler Foster',
    rating: 7.6,
  },
  {
    title: 'Frozen Lanterns Across Aetherwind',
    year: 1983,
    genre: 'Adventure',
    runtime: 120,
    director: 'Parker Ellison',
    rating: 7.3,
  },
  {
    title: 'The Hollowspire Uprising',
    year: 2011,
    genre: 'Fantasy',
    runtime: 132,
    director: 'Rowan Hayes',
    rating: 7.9,
  },
];
